{
  lib,
  buildDartApplication,
  callPackage,
  yosys,
  nextpnr,
  icestorm,
  trellis,
  surfer,
  flakever,
  # openXC7 toolchain package set (from the openxc7 flake input). Null keeps
  # mkFpga on the iCE40/ECP5 path only; spartan7 targets need it.
  openxc7 ? null,
  # openXC7's own pinned nixpkgs, for the python 3.12 deps that prjxray's
  # fasm2frames imports. Null alongside a spartan7 target is a build error.
  openxc7Nixpkgs ? null,
}:
buildDartApplication (finalAttrs: {
  pname = "river-hdl";
  inherit (flakever) version;

  src = ../../.;
  packageRoot = "packages/river_hdl";

  inherit (import ../../nix/common-dart.nix lib)
    pubspecLock
    gitHashes
    ;

  dartEntryPoints = {
    "bin/river-genip" = "packages/river_hdl/bin/river_genip.dart";
    "bin/river-sim" = "packages/river_hdl/bin/river_sim.dart";
  };

  preBuild = ''
    mkdir -p bin
  '';

  # ASIC tapeout/verify are no longer built here: the SoC IP is generated by
  # mkSoC, then handed to asix.mkTapeout / asix.mkVerify in the flake. asix owns
  # the Yosys/OpenROAD/KLayout/Magic/Netgen orchestration.
  passthru = rec {
    mkSoC = callPackage ../river-ip {
      river-hdl = finalAttrs.finalPackage;
      inherit yosys nextpnr surfer;
    };
    mkFpga = callPackage ../river-fpga {
      inherit
        yosys
        nextpnr
        icestorm
        trellis
        openxc7
        openxc7Nixpkgs
        ;
    };
  };
})
