{
  lib,
  buildDartApplication,
  callPackage,
  yosys,
  nextpnr,
  icestorm,
  trellis,
  surfer,
  flakever,
}:
buildDartApplication (finalAttrs: {
  pname = "river-hdl";
  inherit (flakever) version;

  src = ../../.;
  packageRoot = "packages/river_hdl";

  inherit (import ../../nix/common-dart.nix lib)
    pubspecLock
    gitHashes
    ;

  dartEntryPoints = {
    "bin/river-genip" = "packages/river_hdl/bin/river_genip.dart";
    "bin/river-sim" = "packages/river_hdl/bin/river_sim.dart";
  };

  preBuild = ''
    mkdir -p bin
  '';

  # ASIC tapeout/verify are no longer built here: the SoC IP is generated by
  # mkSoC, then handed to asix.mkTapeout / asix.mkVerify in the flake. asix owns
  # the Yosys/OpenROAD/KLayout/Magic/Netgen orchestration.
  passthru = rec {
    mkSoC = callPackage ../river-ip {
      river-hdl = finalAttrs.finalPackage;
      inherit yosys nextpnr surfer;
    };
    mkFpga = callPackage ../river-fpga {
      inherit
        yosys
        nextpnr
        icestorm
        trellis
        ;
    };
  };
})
